// Autogenerated from Pigeon (v5.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.example.qr_scanner;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class QrScannerApi {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class QrScanRequest {
    private @Nullable String instruction;
    public @Nullable String getInstruction() { return instruction; }
    public void setInstruction(@Nullable String setterArg) {
      this.instruction = setterArg;
    }

    public static final class Builder {
      private @Nullable String instruction;
      public @NonNull Builder setInstruction(@Nullable String setterArg) {
        this.instruction = setterArg;
        return this;
      }
      public @NonNull QrScanRequest build() {
        QrScanRequest pigeonReturn = new QrScanRequest();
        pigeonReturn.setInstruction(instruction);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(instruction);
      return toListResult;
    }
    static @NonNull QrScanRequest fromList(@NonNull ArrayList<Object> list) {
      QrScanRequest pigeonResult = new QrScanRequest();
      Object instruction = list.get(0);
      pigeonResult.setInstruction((String)instruction);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class QrScanResult {
    private @Nullable String scannedData;
    public @Nullable String getScannedData() { return scannedData; }
    public void setScannedData(@Nullable String setterArg) {
      this.scannedData = setterArg;
    }

    public static final class Builder {
      private @Nullable String scannedData;
      public @NonNull Builder setScannedData(@Nullable String setterArg) {
        this.scannedData = setterArg;
        return this;
      }
      public @NonNull QrScanResult build() {
        QrScanResult pigeonReturn = new QrScanResult();
        pigeonReturn.setScannedData(scannedData);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(scannedData);
      return toListResult;
    }
    static @NonNull QrScanResult fromList(@NonNull ArrayList<Object> list) {
      QrScanResult pigeonResult = new QrScanResult();
      Object scannedData = list.get(0);
      pigeonResult.setScannedData((String)scannedData);
      return pigeonResult;
    }
  }
  private static class QrScannerApiCodec extends StandardMessageCodec {
    public static final QrScannerApiCodec INSTANCE = new QrScannerApiCodec();
    private QrScannerApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return QrScanRequest.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)129:         
          return QrScanResult.fromList((ArrayList<Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value)     {
      if (value instanceof QrScanRequest) {
        stream.write(128);
        writeValue(stream, ((QrScanRequest) value).toList());
      } else 
      if (value instanceof QrScanResult) {
        stream.write(129);
        writeValue(stream, ((QrScanResult) value).toList());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface QrScannerApi {
    @NonNull QrScanResult scanQrCode(@NonNull QrScanRequest request);

    /** The codec used by QrScannerApi. */
    static MessageCodec<Object> getCodec() {
      return       QrScannerApiCodec.INSTANCE;    }
    /**Sets up an instance of `QrScannerApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, QrScannerApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.QrScannerApi.scanQrCode", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              QrScanRequest requestArg = (QrScanRequest)args.get(0);
              if (requestArg == null) {
                throw new NullPointerException("requestArg unexpectedly null.");
              }
              QrScanResult output = api.scanQrCode(requestArg);
              wrapped.add(0, output);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              wrapped = wrappedError;
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  @NonNull private static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    errorList.add(exception.toString());
    errorList.add(exception.getClass().getSimpleName());
    errorList.add("Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorList;
  }
}
