// Autogenerated from Pigeon (v5.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class QrScanRequest;
@class QrScanResult;

@interface QrScanRequest : NSObject
+ (instancetype)makeWithInstruction:(nullable NSString *)instruction;
@property(nonatomic, copy, nullable) NSString * instruction;
@end

@interface QrScanResult : NSObject
+ (instancetype)makeWithScannedData:(nullable NSString *)scannedData;
@property(nonatomic, copy, nullable) NSString * scannedData;
@end

/// The codec used by QrScannerApi.
NSObject<FlutterMessageCodec> *QrScannerApiGetCodec(void);

@protocol QrScannerApi
/// @return `nil` only when `error != nil`.
- (nullable QrScanResult *)scanQrCodeRequest:(QrScanRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void QrScannerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<QrScannerApi> *_Nullable api);

NS_ASSUME_NONNULL_END
